const players = [
  {
    id: "gk_oliver_kane",
    name: "Oliver Kane",
    preferredPos: "GK",
    finishing: 19,
    passing: 56,
    control: 58,
    defending: 38,
    offBall: 30,
    workRate: 62,
    goalkeeping: 92,
  },
  {
    id: "gk_marco_silva",
    name: "Marco Silva",
    preferredPos: "GK",
    finishing: 15,
    passing: 61,
    control: 60,
    defending: 34,
    offBall: 28,
    workRate: 59,
    goalkeeping: 90,
  },
  {
    id: "gk_daniel_price",
    name: "Daniel Price",
    preferredPos: "GK",
    finishing: 14,
    passing: 53,
    control: 55,
    defending: 36,
    offBall: 26,
    workRate: 64,
    goalkeeping: 89,
  },
  {
    id: "gk_hugo_marin",
    name: "Hugo Marin",
    preferredPos: "GK",
    finishing: 17,
    passing: 58,
    control: 57,
    defending: 35,
    offBall: 27,
    workRate: 61,
    goalkeeping: 88,
  },
  {
    id: "gk_lukas_novak",
    name: "Lukas Novak",
    preferredPos: "GK",
    finishing: 13,
    passing: 55,
    control: 54,
    defending: 33,
    offBall: 24,
    workRate: 57,
    goalkeeping: 87,
  },
  {
    id: "def_aaron_blake",
    name: "Aaron Blake",
    preferredPos: "DEF",
    finishing: 44,
    passing: 70,
    control: 71,
    defending: 92,
    offBall: 64,
    workRate: 88,
    goalkeeping: 8,
  },
  {
    id: "def_mateo_rossi",
    name: "Mateo Rossi",
    preferredPos: "DEF",
    finishing: 42,
    passing: 74,
    control: 73,
    defending: 90,
    offBall: 66,
    workRate: 85,
    goalkeeping: 6,
  },
  {
    id: "def_connor_shaw",
    name: "Connor Shaw",
    preferredPos: "DEF",
    finishing: 39,
    passing: 68,
    control: 70,
    defending: 88,
    offBall: 62,
    workRate: 86,
    goalkeeping: 7,
  },
  {
    id: "def_victor_duarte",
    name: "Victor Duarte",
    preferredPos: "DEF",
    finishing: 36,
    passing: 65,
    control: 67,
    defending: 86,
    offBall: 61,
    workRate: 84,
    goalkeeping: 5,
  },
  {
    id: "def_ben_carter",
    name: "Ben Carter",
    preferredPos: "DEF",
    finishing: 41,
    passing: 72,
    control: 69,
    defending: 84,
    offBall: 63,
    workRate: 87,
    goalkeeping: 6,
  },
  {
    id: "mid_julian_costa",
    name: "Julian Costa",
    preferredPos: "MID",
    finishing: 72,
    passing: 92,
    control: 91,
    defending: 68,
    offBall: 88,
    workRate: 86,
    goalkeeping: 4,
  },
  {
    id: "mid_ryan_patel",
    name: "Ryan Patel",
    preferredPos: "MID",
    finishing: 69,
    passing: 89,
    control: 90,
    defending: 66,
    offBall: 86,
    workRate: 84,
    goalkeeping: 5,
  },
  {
    id: "mid_leo_tanaka",
    name: "Leo Tanaka",
    preferredPos: "MID",
    finishing: 67,
    passing: 88,
    control: 87,
    defending: 64,
    offBall: 85,
    workRate: 90,
    goalkeeping: 3,
  },
  {
    id: "mid_marcus_boyd",
    name: "Marcus Boyd",
    preferredPos: "MID",
    finishing: 70,
    passing: 86,
    control: 84,
    defending: 62,
    offBall: 83,
    workRate: 88,
    goalkeeping: 2,
  },
  {
    id: "mid_elias_haddad",
    name: "Elias Haddad",
    preferredPos: "MID",
    finishing: 65,
    passing: 84,
    control: 85,
    defending: 65,
    offBall: 82,
    workRate: 87,
    goalkeeping: 4,
  },
  {
    id: "fwr_diego_alvarez",
    name: "Diego Alvarez",
    preferredPos: "FWR",
    finishing: 92,
    passing: 71,
    control: 83,
    defending: 37,
    offBall: 91,
    workRate: 78,
    goalkeeping: 2,
  },
  {
    id: "fwr_samir_khan",
    name: "Samir Khan",
    preferredPos: "FWR",
    finishing: 91,
    passing: 69,
    control: 82,
    defending: 35,
    offBall: 90,
    workRate: 76,
    goalkeeping: 3,
  },
  {
    id: "fwr_lucas_meyer",
    name: "Lucas Meyer",
    preferredPos: "FWR",
    finishing: 90,
    passing: 68,
    control: 80,
    defending: 33,
    offBall: 88,
    workRate: 74,
    goalkeeping: 1,
  },
  {
    id: "fwr_noah_ibrahim",
    name: "Noah Ibrahim",
    preferredPos: "FWR",
    finishing: 89,
    passing: 66,
    control: 79,
    defending: 34,
    offBall: 87,
    workRate: 75,
    goalkeeping: 2,
  },
  {
    id: "fwr_tyler_grant",
    name: "Tyler Grant",
    preferredPos: "FWR",
    finishing: 88,
    passing: 70,
    control: 81,
    defending: 36,
    offBall: 85,
    workRate: 77,
    goalkeeping: 2,
  },
];

export default players;
